using estacionamiento_adn.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.Data.SqlClient;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace AdnFabioRamos.Infrastructure.Persistence
{
    public partial class Adn_CeibaContext
    {
        private Adn_CeibaContextProcedures _procedures;

        public Adn_CeibaContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new Adn_CeibaContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public Adn_CeibaContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class Adn_CeibaContextProcedures
    {
        private readonly Adn_CeibaContext _context;

        public Adn_CeibaContextProcedures(Adn_CeibaContext context)
        {
            _context = context;
        }

        public virtual async Task<List<sp_movimientos_parqueoResult>> sp_movimientos_parqueoAsync(int? codpar, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new[]
            {
                new SqlParameter
                {
                    ParameterName = "codpar",
                    Value = codpar ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_movimientos_parqueoResult>("EXEC @returnValue = [par].[sp_movimientos_parqueo] @codpar", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_validar_pico_placaResult>> sp_validar_pico_placaAsync(int? tipo_vehiculo, string placa, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new[]
            {
                new SqlParameter
                {
                    ParameterName = "tipo_vehiculo",
                    Value = tipo_vehiculo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "placa",
                    Size = 25,
                    Value = placa ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_validar_pico_placaResult>("EXEC @returnValue = [pp].[sp_validar_pico_placa] @tipo_vehiculo, @placa", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
