// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace estacionamiento_adn.Models
{
    [Table("cap_capacidad", Schema = "par")]
    public partial class cap_capacidad
    {
        [Key]
        public int cap_codigo { get; set; }
        public int cap_codpar { get; set; }
        public int cap_codtipt { get; set; }
        [Column("cap_capacidad")]
        public short cap_capacidad1 { get; set; }
        public double cap_valor_hora { get; set; }
        public double cap_valor_dia { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? cap_fecha_creacion { get; set; }
    }
}