// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace estacionamiento_adn.Models
{
    [Table("par_parqueo", Schema = "par")]
    public partial class par_parqueo
    {
        [Key]
        public int par_codigo { get; set; }
        [Required]
        [StringLength(50)]
        public string par_nombre { get; set; }
        [Required]
        [StringLength(255)]
        public string par_direccion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? par_fecha_creacion { get; set; }
    }
}