// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace estacionamiento_adn.Models
{
    [Table("tipt_tipo_transporte", Schema = "par")]
    public partial class tipt_tipo_transporte
    {
        [Key]
        public int tipt_codigo { get; set; }
        [Required]
        [StringLength(50)]
        public string tipt_tipo { get; set; }
        [Required]
        [StringLength(75)]
        public string tipt_descripcion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? tipt_fecha_creacion { get; set; }
    }
}