// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace estacionamiento_adn.Models
{
    [Table("dpp_detalle_pico_placa", Schema = "pp")]
    public partial class dpp_detalle_pico_placa
    {
        [Key]
        public int dpp_codigo { get; set; }
        public int dpp_codpp { get; set; }
        public int dpp_codtipt { get; set; }
        /// <summary>
        /// 1: Enero ... 12: Diciembre
        /// </summary>
        public byte dpp_mes { get; set; }
        [Required]
        [StringLength(5)]
        public string dpp_hora_inicio { get; set; }
        [Required]
        [StringLength(5)]
        public string dpp_hora_fin { get; set; }
        /// <summary>
        /// 1: Lunes ... 7: Domingo
        /// </summary>
        public int dpp_dia_semana { get; set; }
        public short dpp_digito { get; set; }
        /// <summary>
        /// Que la placa I: Inicie, F: Finalice
        /// </summary>
        [Required]
        [StringLength(2)]
        public string dpp_digito_inicio_final { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? dpp_fecha_creacion { get; set; }
    }
}