// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace estacionamiento_adn.Models
{
    [Table("pp_pico_placa", Schema = "pp")]
    public partial class pp_pico_placa
    {
        [Key]
        public int pp_codigo { get; set; }
        public int pp_anio { get; set; }
        [Required]
        [StringLength(255)]
        public string pp_descripcion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? pp_fecha_creacion { get; set; }
    }
}