// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace estacionamiento_adn.Models
{
    public partial class sp_validar_pico_placaResult
    {
        public int dpp_codigo { get; set; }
        public int dpp_codpp { get; set; }
        public int dpp_codtipt { get; set; }
        public byte dpp_mes { get; set; }
        public string dpp_hora_inicio { get; set; }
        public string dpp_hora_fin { get; set; }
        public int dpp_dia_semana { get; set; }
        public string dia_nombre { get; set; }
        public short dpp_digito { get; set; }
        public string dpp_digito_inicio_final { get; set; }
        public string salida { get; set; }
        public int tipo { get; set; }
    }
}
